local view = require("game.view")

function init(self)
	msg.post(".", "acquire_input_focus")
end

function on_message(self, message_id, message, sender)
	if message_id == hash("initialize") then
		self.level_view = view.create_view(message.level)
	else
		pprint({ "level.script", message_id, message, sender })
	end
end

function update(self, dt)
	view.update(self.level_view)
end

function on_input(self, action_id, action)
	view.on_input(self.level_view, action_id, action)
end
