function init(self)
	msg.post(".", "acquire_input_focus")
	msg.post("@render:", "use_fixed_fit_projection", { near = -1, far = 1 })
	msg.post("#level", "async_load")
end

function on_message(self, message_id, message, sender)
	if message_id == hash("proxy_loaded") then
		msg.post("level:/root#controller", "initialize", { level = 1 })
		msg.post("#level", "enable")
	else
		pprint({ "main.script", message_id, message, sender })
	end
end
